### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by AsheshPlays** [Ether2023/Ether-Uprotector#2]
Hello! I have some questions regarding these repos. I have tried few obfuscators and such but they just dont work good enough. So here are my questions:

1. Will this protect my mmorpg mobile game?
2. Can this encrypt my game?
3. Does it have AssetBundles protection?

My main concern is how can i protect my model assets from being extracted?

**Comment by AsheshPlays** [comment]
This is very good to hear. Right now, I am scared to release my game even for Beta. Its a mobile MMORPG Game. And I am still looking for a good protection. I hope your team will bring great news soon.

**Comment by AsheshPlays** [comment]
@SummerofOrange 

Hello there! May i know what is the current update on this?

**Comment by SummerofOrange** [comment]
**[EtherTeam]**
I'm glad to receive your reply. At present, the latest version of EtherUpprotector is `v1.6std1.5`. The updated content is as follows:

1. The new UI can make your configuration easier
2. Fixed bugs of program errors after the `Android` platform was built
3. Support the confusion of `Monobehaviour Type`
4. Automatically analyze the project and generate the method name and field name to be ignored according to the project generation configuration (including `GUI`, `Animation` and `Reflection`)

You can find more details in our document, and learn how to configure your encryption scheme and the description of each function in [[How to start]](https://github.com/Ether2023/Ether-Uprotector/tree/main/Ether_Obfuscator)

The above is all. If you don't understand anything, you can put it forward in this `issue`, and we will answer it for you :D
