### ISSUE TITLE
Recommendations

### ISSUE THREAD

**Issue by AsheshPlays** [Ether2023/Ether-Uprotector#3]
Hello! It's me again. As I mention from my previous issue post, i am developing a mmorpg mobile game, I want to know if what do you recommend or suggest to use to atleast protect my game? And if there are also settings I should do when using your repos. Thanks you and will be waiting for a response.

**Comment by SummerofOrange** [comment]
**[Ether Team]**

Hello, here is Ether Team, here are some answers to your questions:

1. Our new version of the Confuser will be released soon (within 2 days). It will be much more powerful and simplified to use. You can try our new version of the Confuser (v1.6std1)

![1](https://user-images.githubusercontent.com/49600578/214488989-dc52b140-1a88-49ef-b8ab-d3fa3de7d509.png)

2. Why not try `Anti-Cheat Toolkit` , a free plugin, it protects your game memory from being modified

3. With respect to resource protection, we have developed an interface for `Unity Asset` (which you can find in the `dev` branch) and made a breakthrough on this issue, but how to achieve protection is still a long-term plan (which cannot be achieved in the near future). You can try encapsulating your asset files with `AssetBundle` and encrypting them binary, then decrypting and loading them using the `LoadFromMemory` method

**Comment by SummerofOrange** [comment]
4. About how to configure your obfuscator configuration file, we will mention this issue in the new document

**Comment by AsheshPlays** [comment]
@SummerofOrange
Thank you for the response and I look forward to that update in 2 days. Please add a guide once you release the repo. Ill be using it and testing it as soon as possible.


Regards!

Ashesh,
Tantra Genesis Mobile

**Comment by AsheshPlays** [comment]
@SummerofOrange 
How do i know if it is working properly? What tools do i need to use to compare both my APK?

**Comment by SummerofOrange** [comment]
**[EtherTeam]**
- On this issue, first of all, you should check the output information of Unity to see if there is any information about confusion and successful construction

- Second, you should test whether your apk works properly

- Finally, you can decompress your apk. According to your `ScriptingBackend` configuration, if it is `Mono`, you can use the `Assembly-CSharp.dll` in the [DnSpyEx](https://github.com/dnSpyEx/dnSpy) decompile decompression folder to check the confusion and test its security. If it is `IL2CPP`, you can use [IL2CPPDumper](https://github.com/Perfare/Il2CppDumper) to obtain `Assembly-CSharp-dump.dll` first, and then repeat the above steps

**Comment by AsheshPlays** [comment]
Hello! Its me again.. I really hoped we have better contact soon. Anyways, I have configured my game, parts of it, like a demo. And all works without the Ether. Now, since its working, I imported the Ether. And I see it doesn't support IL2CPP? My APK is built on IL2CPP. Is there a way? Or I am using 1.6std1.5. Any suggestions?

![image](https://user-images.githubusercontent.com/118698151/215783612-2b7a931e-2b6c-4ef9-9cff-e14e7987cc17.png)

**Comment by SummerofOrange** [comment]
**[EtherTeam]**
Thank you for your question:

I think you have misunderstood our meaning. **Ether Obfuscator** fully supports `IL2CPP` construction. In fact, **only `PEPacker `and `MethodError` do not support IL2CPP construction**. Our prompt is to tell you that if you use IL2CPP construction, even if you enable the two functions of PEPacker and MethodError, they will not work in fact, and it has no impact on other functions. **Your project is still protected by Ether.**

At the same time, our `EtherIL2CPP` *(an upgraded version based on [the old version of EtherIL2CPP](https://github.com/Ether2023/Ether-Uprotector/tree/main/Ether_IL2CPP))* will soon be released in `v1.6std2`. Compared with the original IL2CPP, it has **higher security and better compatibility**. If you use IL2CPP to build your project, you can try new `EtherIL2CPP` in the near future. xD

**Comment by AsheshPlays** [comment]
@SummerofOrange

Hey! Its me again and again.. XD.. so i tried it again.. made different configs but there are 2 classes that always gets error after doing it.I tried adding it on ignore but still gets error..
Any suggestions how can i fix it.. Its DbServiceClient and ExecuteReader.

**Comment by SummerofOrange** [comment]
Thank you for your feedback. I'm sorry to hear that your build failed. The Ether Upprotector project is still in its early stage. It does have many problems to solve. Maybe you can add my Potato(@ oRangeSumMer) so that we can exchange more detailed information, so that I can better help you.

Secondly, we hope you can provide more detailed information about the error, such as the result of the error and which function caused the error, or show me your configuration file, which can help me solve your problem and fix the bug faster

**Comment by AsheshPlays** [comment]
I just downloaded Potato, its my first time using it. Also heard it for the first time. I also appreciate your responding to my issues even though you can just ignore me. 😊

Ill be adding you on potato.
